apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-qugitrhv
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/go-qugitrhv:2edd36578b36f104d3d0210c035a2442f6a8e461@sha256:db7283e535936bd3564619785aacb823fc9d0512ff2da46fc11b75ba0c477282
          name: container-image
